
CONTIKI_TARGET_SOURCEFILES+=

PLATFORMAPPS+=ip64

include $(MIST)/contiki/platform/native/Makefile.native

CFLAGS += -I$(MIST)/platform/mist-native
CFLAGS += -I$(MIST)/contiki/platform/native


vpath %.c $(MIST)/platform/mist-native/ $(MIST)/contiki/platform/native/\
          $(MIST)/contiki/platform/native/dev \
          $(MIST)/contiki/platform/native/ctk


