ARCH_RADIO_SOURCES=cc1101-msp-arch.c
PLATFORMAPPS+=cc1101
CFLAGS += -I$(MIST)/platform/$(TARGET)

vpath %.c $(MIST)/platform/trxeb
vpath %.h $(MIST)/platform/trxeb
vpath %.S $(MIST)/platform/trxeb
CFLAGS += -I $(MIST)/platform/trxeb

CONTIKI_TARGET_SOURCEFILES+=enc28j60-arch.c

include $(MIST)/platform/trxeb/Makefile.trxeb

PLATFORMAPPS += enc28j60
contiki-$(TARGET).a: ${addprefix $(OBJECTDIR)/,symbols.o}
#	$(AR) rcf $@ $^
