ARCH_RADIO_SOURCES=cc1101-msp-arch.c
PLATFORMAPPS+=cc1101
CFLAGS += -DCC1101=1
include $(MIST)/platform/mist-exp5438/Makefile.mist-exp5438

contiki-$(TARGET).a: ${addprefix $(OBJECTDIR)/,symbols.o}
#	$(AR) rcf $@ $^

vpath %.c $(MIST)/platform/mist-exp5438
vpath %.h $(MIST)/platform/mist-exp5438
vpath %.S $(MIST)/platform/mist-exp5438
CFLAGS += -I $(MIST)/platform/mist-exp5438
